# Generated by Django 5.0.1 on 2024-01-02 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='style',
            options={'verbose_name': 'Стиль', 'verbose_name_plural': 'Стили'},
        ),
        migrations.CreateModel(
            name='StyleInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Фотография')),
                ('place_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_info', to='secondary.style')),
            ],
            options={
                'unique_together': {('place_info', 'image')},
            },
        ),
    ]
