# Generated by Django 5.0.1 on 2024-01-03 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothesColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='color_image1', verbose_name='Фото для рассветки 1 ')),
                ('image2', models.ImageField(upload_to='color_image2', verbose_name='Фото  для рассветки 2')),
                ('image3', models.ImageField(upload_to='color_image3', verbose_name='Фото  для рассветки 3')),
                ('title', models.CharField(max_length=255, verbose_name='Название товара')),
                ('desctiptions', models.TextField(verbose_name='Описание')),
                ('now_price', models.CharField(max_length=255, verbose_name='Цена сейчас')),
                ('before_price', models.CharField(max_length=255, verbose_name='Цена раньше')),
            ],
            options={
                'verbose_name': 'Одежды с рассветкой',
                'verbose_name_plural': 'Одежды с рассветками',
            },
        ),
    ]
