# Generated by Django 5.0.1 on 2024-01-03 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0002_clothescolor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothescolor',
            old_name='desctiptions',
            new_name='descriptions',
        ),
    ]
