# Generated by Django 5.0 on 2024-01-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0002_faqs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faqs',
            name='image',
        ),
        migrations.AddField(
            model_name='faqs',
            name='answer',
            field=models.TextField(default=1, verbose_name='Ответ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faqs',
            name='question',
            field=models.CharField(default=1, max_length=155, verbose_name='Вопрос'),
            preserve_default=False,
        ),
    ]
