# Generated by Django 5.0.1 on 2024-01-03 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0003_rename_desctiptions_clothescolor_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothescolor',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='color_image1', verbose_name='Фото для рассветки 1 '),
        ),
        migrations.AlterField(
            model_name='clothescolor',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='color_image2', verbose_name='Фото  для рассветки 2'),
        ),
        migrations.AlterField(
            model_name='clothescolor',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='color_image3', verbose_name='Фото  для рассветки 3'),
        ),
    ]
