# Generated by Django 5.0.1 on 2024-01-02 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0003_glance_glanceinfo1_glanceinfo2'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='glanceinfo2',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='glanceinfo2',
            name='place_info',
        ),
        migrations.CreateModel(
            name='GlanceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Фотография сверху')),
                ('place_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glance_info', to='secondary.glance')),
            ],
            options={
                'unique_together': {('place_info', 'image')},
            },
        ),
        migrations.DeleteModel(
            name='GlanceInfo1',
        ),
        migrations.DeleteModel(
            name='GlanceInfo2',
        ),
    ]
