# Generated by Django 5.0.1 on 2024-01-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0004_alter_glanceinfo2_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='glance',
            options={'verbose_name': 'Категория взгляда', 'verbose_name_plural': 'Категории взгляда'},
        ),
        migrations.AddField(
            model_name='glanceinfo',
            name='title',
            field=models.CharField(default=1, max_length=255, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
