# Generated by Django 5.0.1 on 2024-01-03 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0004_alter_clothescolor_image1_alter_clothescolor_image2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptions', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Последняя новость',
                'verbose_name_plural': 'Последнии новости',
            },
        ),
        migrations.AlterField(
            model_name='clothescolor',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='color_image1/', verbose_name='Фото для рассветки 1 '),
        ),
        migrations.AlterField(
            model_name='clothescolor',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='color_image2/', verbose_name='Фото  для рассветки 2'),
        ),
        migrations.AlterField(
            model_name='clothescolor',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='color_image3/', verbose_name='Фото  для рассветки 3'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='image',
            field=models.ImageField(upload_to='partner_image/', verbose_name='Фотография '),
        ),
        migrations.AlterField(
            model_name='trends',
            name='card_image',
            field=models.ImageField(upload_to='card_image/', verbose_name='Фото внутри карточки'),
        ),
        migrations.AlterField(
            model_name='trends',
            name='image',
            field=models.ImageField(upload_to='trends_image/', verbose_name='Большое фото'),
        ),
        migrations.CreateModel(
            name='NewsInline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news_image/', verbose_name='Фотография')),
                ('mini_descriptions', models.TextField(max_length=255, verbose_name='Мини описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('place_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lastnews_info', to='secondary.news')),
            ],
            options={
                'unique_together': {('place_info', 'image')},
            },
        ),
    ]
