# Generated by Django 5.0.1 on 2024-01-02 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0007_collection_collectioninline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'verbose_name': 'Коллекция', 'verbose_name_plural': 'Коллекции'},
        ),
    ]
