# Generated by Django 5.0.1 on 2024-01-02 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0008_alter_collection_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectioninline',
            name='place_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_info', to='secondary.collection'),
        ),
    ]
