# Generated by Django 5.0.1 on 2024-01-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0009_alter_collectioninline_place_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectioninline',
            name='size',
            field=models.CharField(default=1, max_length=255, verbose_name='Размеры'),
            preserve_default=False,
        ),
    ]
