# Generated by Django 5.0.1 on 2024-01-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0010_collectioninline_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mini_descriptions', models.TextField(max_length=255, verbose_name='Мини описание')),
                ('image', models.ImageField(upload_to='testimonials/image', verbose_name='Фото клиентов')),
                ('testimonial', models.TextField(verbose_name='Отзыв')),
                ('name', models.CharField(max_length=255, verbose_name='Имя клиента')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
