# Generated by Django 5.0.1 on 2024-01-02 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0011_testimonials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonials',
            name='image',
        ),
        migrations.RemoveField(
            model_name='testimonials',
            name='name',
        ),
        migrations.RemoveField(
            model_name='testimonials',
            name='testimonial',
        ),
        migrations.CreateModel(
            name='TestimonialsInline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='testimonials/image', verbose_name='Фото клиентов')),
                ('testimonial', models.TextField(verbose_name='Отзыв')),
                ('name', models.CharField(max_length=255, verbose_name='Имя клиента')),
                ('place_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials_info', to='secondary.testimonials')),
            ],
            options={
                'unique_together': {('place_info', 'image')},
            },
        ),
    ]
