# Generated by Django 5.0.1 on 2024-01-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0012_remove_testimonials_image_remove_testimonials_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_descrip', models.TextField(verbose_name='Главное описание')),
                ('image', models.ImageField(upload_to='trends_image', verbose_name='Большое фото')),
                ('goods', models.ImageField(upload_to='goods/trend/image', verbose_name='Фото товара')),
                ('card_image', models.ImageField(upload_to='card_image', verbose_name='Фото внутри карточки')),
                ('title', models.CharField(max_length=255, verbose_name='Название товара')),
                ('descriptions', models.TextField(verbose_name='Описание товара')),
                ('now_price', models.CharField(max_length=255, verbose_name='Цена сейчас')),
                ('before_price', models.CharField(max_length=255, verbose_name='Цена раньше')),
                ('size', models.CharField(max_length=255, verbose_name='Размеры')),
            ],
            options={
                'verbose_name': 'Товар Тренд',
                'verbose_name_plural': 'Товары Тренды',
            },
        ),
    ]
