# Generated by Django 5.0.1 on 2024-01-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0013_trends'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='partner_image', verbose_name='Фотография ')),
            ],
            options={
                'verbose_name': 'Парнер',
                'verbose_name_plural': 'Партнеры',
            },
        ),
    ]
