# Generated by Django 5.0.1 on 2024-01-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0014_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image_art', verbose_name='Фото')),
                ('part', models.CharField(max_length=255, verbose_name='Название части')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('descriptions', models.TextField(verbose_name='Описание товара')),
            ],
            options={
                'verbose_name': 'Отдел товаров',
                'verbose_name_plural': 'Отделы товаров',
            },
        ),
    ]
