# Generated by Django 5.0.1 on 2024-01-02 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0015_art'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art',
            name='image',
        ),
    ]
